version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: .
    ports:
      - '8081:8081'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
